Algoritmo "semnome"



Var

nomeUsuario: vetor[1..3] de caractere
senhaUsuario: vetor[1..3] de caractere
contador:inteiro


Inicio

para contador de 1 ate 3 passo 1 faca

escreva("Digite Nome:")
leia(nomeUsuario[contador])

escreva("Digite Senha:")
leia(senhaUsuario[contador])

fimPara

escreval("")


para contador de 1 ate 3 passo 1 faca


escreval ("Nome: ", nomeUsuario[contador]," Senha: ",senhaUsuario[contador],"na ", contador,"º posição")

fimPara

Fimalgoritmo